language: node_js
node_js:
  - '0.10'
  - '0.12'
  - 4
  - 5

after_script:
  - npm run coverage

env:
  global:
    secure: "POPhbUFA5+AlJrba8bEbyHwTSs/13Wric+eUwey0N6Isd8Gj43EuuINrVbHcSgk8LAjqrBG/nt4iWWsB+cb8tn4oXG3stV1D6ZlLh33m2iDBZMkh6rfyGvtoIuD1j06JJ4JVGJFkLcIwohDhLmavg1MYrqDiGBmd5Q9it8XQfrY="

notifications:
  slack:
    secure: "g7MOXqNzfO17NmRZQ7GJqOvcnOKYuPTCBD4DHAUBdNRZq8POxjWkKKPK9kZPE+ALt5NtyILhUp2s+lM9w7Z5BwdlYciGacvwdre/pVuMDdfb9hJaeiT+2HT1rtcgDsL+W0E8KawIJmXO/MiZQNyv8I2g4jjY2KsfQ5dRAt+ZT70="
